version: '3.8'

services:
  jenkins:
    container_name: jenkins
    build: .
    image: jenkins:latest
    mem_reservation: 8GB
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./configurations:/var/configurations
    secrets:
      - jenkins_admin_user
      - github_http
    environment:
      CASC_JENKINS_CONFIG: /var/configurations
      JENKINS_HOME: /var/jenkins_home
    env_file:
      - .env

secrets:
  jenkins_admin_user:
    file: secrets/jenkins_admin_user
  github_http:
    file: secrets/github_http

volumes:
  jenkins_home:
