#!groovy

node('jenkins') {
    stage("scm") {
        checkout scm
    }

    stage('code quality') {
        sh "${env.WORKSPACE}/shared-library/gradlew codenarcAllSources"
    }

    stage('test') {
        sh "${env.WORKSPACE}/shared-library/gradlew test"
    }

    stage('integration test') {
        sh "${env.WORKSPACE}/shared-library/gradlew integrationTest"
    }
}
